/**
 * NUMBERS- When writing application, one needs numnbers
 *  ie, youtube display number of subscribers for each channel
 * number of likes for each video
 * total hits when logged into google.com
 * We have whole numbers known as integer
 * ie- 2, 500, 1000,7 , positive or negative numbers are all intger- -5, -4, 0 etc.
 * but in online shop when you display prices, it uses decimal numbers you use whole number or decimal numbers.
 * ie like Amazons ratings-3.5, 0.0, 80.99 they equally consists of negative and positive numbers--4.40, -6.00
 * STRING: This is basically everything you see on your keyboard. All the letters , numbers, special characters like &, %, @.
 * Java scripts identifies variables by the user using quotes; which could be single or double quotes "", ''.
 * ie, "3" is a string, "a" is eqally a quote even letters from non english. combination of letters & numbers. email
 *Character consists of single keys- "a", "3" while strings consists of zero or multiple characters-"username12"
 BOOLEAN: Developers write js codes that validates whether information you nprovided is wrong or correct.
 To express that incorrect or correct state, booleans are used. (True/False) Enter wrong password when logging into your application,
  usually get a message you provided a wrong password or wrong email address or  invalid credit card when buying ticket.
   Just like in string "false" is a string, while false without quote is a boolean expression.
   Thats how js can differenciate between those two.True/false can also be used for a simple yes/no situation like is aparatment available ? 
   yes/no , or is the user logged in? yes/no.
   ARRAY: This expresses list. This type of application that display list of same kind of data like list of friends on fb 
   or list of available apartments at M&B, or list of comments for instagram post.
   List have their own datatype in all programming languages but in js, its datatype is array.
   ei- list of friends name would appear like this ["friend1", "friend2", "friend3", "friend4"] It includes multiple names.
   All the syntax in array encloses in square bracket[].You can also have list of ratings for Amazons products
   ie [3,10,6] array with numbers. it contains d/f datatypes too, first we have list of strings, and now we have numbers.
   In js , you can mix d/f datatypes inside array, both integers and decimals.
   OBJECT: In the amazons review for example, you dont just view reviews, you also see the  authors names and text tey wrote
   you have all the informations grouped in one item, you express these using objective datatype. The syntax will be in 
   curly brackects{ It is important so that js will understand the data type were writting.} Another example is an available
   apartment which includes other attribute it will have like location, price, description avalaibity , images etc.
   Its more information inside. When you write, js highlights d/f datatypes. You can also use any datatype as a value inside the object.
