/**
 * variable is a medium to which we store data,
 * it can be reffered to as box to which data
 * is stored
 * 
 * types
 * const -constant = this is usedto store data
 * that are constant and do not change like name
 * for example
 * 
 * var = this is used to store data that is flexible
 * and prone to change overtime through the
 * life time of the code: name
 * let = is similar to {var} in the sense that
 * it's used to store flexible data
 * 
 * structure
 * (variabes name) (data name) ={assignmet} (data)
 * 
 * ---Example
 * const name ="sammy james"
 * var age = 30
 * let ageTwo = 50
 * 
 * ---Rules
 * data name must follow snake-case or
 * camelCase structure
 * -two variable can't share the same name
 * -numbers should not be added to variable names
 * -don't use a keyword as a variable name
 */